spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/session
    username: pavel
    password: pavel
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
session:
  cron: "01 00 00 * * *"
  clean:
    enabled: true
